version: '2.2'
services:
  mysql:
    image: mysql
    container_name: soap_api_db
    ports:
      - "3307:3306"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_USER=ok
      - MYSQL_ROOT_PASSWORD=ok
      - MYSQL_ROOT_DATABASE=soap_api_db

  java:
    build: .
    container_name: soap_api_server
    ports:
      - "8001:8001"
    depends_on:
      - mysql
    volumes:
      - ./target/SOAP_API_WBD-1.0-SNAPSHOT-jar-with-dependencies.jar:/app/target/SOAP_API_WBD-1.0-SNAPSHOT-jar-with-dependencies.jar

volumes:
  data:
